// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJ1Dv04V6sOXzk7OZ76glVQVdS6ngC0Q',
    appId: '1:84388751721:web:7f4d8cf3d7cb2aead935f8',
    messagingSenderId: '84388751721',
    projectId: 'registration-app-goteri141',
    authDomain: 'registration-app-goteri141.firebaseapp.com',
    storageBucket: 'registration-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3TTmlwD9a6bTDzSSlG3A5hgDR9IqN7M',
    appId: '1:84388751721:android:309982c5ab4118e0d935f8',
    messagingSenderId: '84388751721',
    projectId: 'registration-app-goteri141',
    storageBucket: 'registration-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluubM9pdBPQ45OADUA5kHi5EO4LVgAZQ',
    appId: '1:84388751721:ios:0654707d1917fa90d935f8',
    messagingSenderId: '84388751721',
    projectId: 'registration-app-goteri141',
    storageBucket: 'registration-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluubM9pdBPQ45OADUA5kHi5EO4LVgAZQ',
    appId: '1:84388751721:ios:0654707d1917fa90d935f8',
    messagingSenderId: '84388751721',
    projectId: 'registration-app-goteri141',
    storageBucket: 'registration-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSJ1Dv04V6sOXzk7OZ76glVQVdS6ngC0Q',
    appId: '1:84388751721:web:4f705217c8af1b4ad935f8',
    messagingSenderId: '84388751721',
    projectId: 'registration-app-goteri141',
    authDomain: 'registration-app-goteri141.firebaseapp.com',
    storageBucket: 'registration-app-goteri141.firebasestorage.app',
  );
}
